function enableSafe()
	playerBlood = getElementData(localPlayer, "blood")
	setElementData(localPlayer, "god", true)
	playerTimer = setTimer(function() 
							toggleControl("fire", true)
							toggleControl("zoom_in", false)
							toggleControl("vehicle_fire", false)
							toggleControl("action", false)
							setElementData(localPlayer, "blood", playerBlood, true)
							
							end, 500,0)
